# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  # Use Node.js
  - task: NodeTool@0
    inputs:
      versionSpec: "20.x"
    displayName: "Use Node.js 20.x"

  # Install dependencies
  - script: |
      npm install
    displayName: "Install dependencies"

  # Build the TypeScript project
  - script: |
      npm run build
    displayName: "Build TypeScript project"

  # Copy Procfile to dist folder
  - script: |
      cp Procfile dist/
    displayName: "Copy Procfile to dist folder"

  # Package the built application
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: "$(Build.SourcesDirectory)/dist"
      includeRootFolder: false
      archiveType: "zip"
      archiveFile: "$(Build.ArtifactStagingDirectory)/node-express-app_$(Build.BuildNumber).zip"
      replaceExistingArchive: true
    displayName: "Package built application"

  # Publish build artifacts
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)"
      ArtifactName: "node-express-app"
    displayName: "Publish build artifacts"
